// import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./components/nav";
import "bootstrap/dist/css/bootstrap.min.css";
import 'react-toastify/dist/ReactToastify.css';


// const geistSans = localFont({
//   // src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   // src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Souq On",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
      <html lang="en">
        <body className={` antialiased`}>
          <NavBar />
          {children}
        </body>
      </html>
  );
}
